//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DAB_PLAYER.rc
//
#define IDD_DAB_PLAYER_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDB_BITMAP2                     130
#define IDB_CHAN_CCTV1                  130
#define IDB_BITMAP3                     131
#define IDB_CHAN_CCTV2                  131
#define IDB_BITMAP4                     132
#define IDB_CHAN_DYCJ1                  132
#define IDB_BITMAP5                     133
#define IDB_CHAN_DYCJ2                  133
#define IDB_BITMAP6                     134
#define IDB_SCREEN_RIGHT                134
#define IDB_BITMAP7                     135
#define IDB_CHAN_ENEWS1                 135
#define IDB_BITMAP8                     136
#define IDB_CHAN_ENEWS2                 136
#define IDB_BITMAP9                     137
#define IDB_CHAN_SGJT1                  137
#define IDB_BITMAP10                    138
#define IDB_CHAN_SGJT2                  138
#define IDB_BITMAP11                    139
#define IDB_FRAME_UPBOARD               139
#define IDB_BITMAP12                    140
#define IDB_FRAME_UPSIDE                140
#define IDB_BITMAP13                    141
#define IDB_FRAME_LRSIDE                141
#define IDB_BITMAP14                    142
#define IDB_FRAME_MIDSIDE               142
#define IDB_BITMAP15                    143
#define IDB_FRAME_ROLLBAR               143
#define IDB_BITMAP16                    144
#define IDB_FRAME_DOWNSIDE              144
#define IDB_BITMAP18                    146
#define IDB_VOL_DOWN                    146
#define IDB_BITMAP19                    147
#define IDB_VOL_UP                      147
#define IDB_BITMAP20                    148
#define IDB_MENU_VIDEO                  148
#define IDB_BITMAP21                    149
#define IDB_MENU_AUDIO                  149
#define PIC_EXIT                        150
#define IDB_MENU_EXIT                   150
#define IDB_BITMAP23                    151
#define IDB_SIGNAL0                     151
#define IDB_BITMAP24                    152
#define IDB_SIGNAL1                     152
#define IDB_BITMAP25                    153
#define IDB_SIGNAL2                     153
#define IDB_SIGNAL3                     154
#define IDB_BITMAP27                    155
#define IDB_SIGNAL4                     155
#define IDB_BITMAP28                    156
#define IDB_SIGNAL5                     156
#define IDB_BITMAP29                    157
#define IDB_VOL_BAR00                   157
#define IDB_BITMAP30                    158
#define IDB_B                           158
#define IDB_VOL_BAR01                   158
#define IDB_BITMAP31                    159
#define IDB_VOL_BAR02                   159
#define IDB_BITMAP32                    160
#define IDB_VOL_BAR03                   160
#define IDB_BITMAP33                    161
#define IDB_VOL_BAR04                   161
#define IDB_BITMAP34                    162
#define IDB_VOL_BAR05                   162
#define IDB_BITMAP35                    163
#define IDB_VOL_BAR06                   163
#define IDB_BITMAP36                    164
#define IDB_VOL_BAR07                   164
#define IDB_BITMAP37                    165
#define IDB_VOL_BAR08                   165
#define IDB_BITMAP38                    166
#define IDB_VOL_BAR09                   166
#define IDB_BITMAP39                    167
#define IDB_VOL_BAR10                   167
#define IDB_BITMAP40                    168
#define IDB_VOL_BAR11                   168
#define IDB_BITMAP41                    169
#define IDB_VOL_BAR12                   169
#define IDB_BITMAP42                    170
#define IDB_VOL_BAR13                   170
#define IDB_BITMAP43                    171
#define IDB_VOL_BAR14                   171
#define IDB_BITMAP44                    172
#define IDB_VOL_BAR15                   172
#define IDB_BITMAP45                    173
#define IDB_VOL_BAR16                   173
#define PIC_rRight                      175
#define IDB_MENU_RIGHT                  175
#define IDB_SCREEN0                     176
#define IDB_SCREEN1                     177
#define IDB_BITMAP48                    178
#define IDB_SCREEN2                     178
#define IDB_tLeft                       179
#define IDB_MANU_LEFT                   179
#define IDB_MENU_VIDEO2                 181
#define IDB_MENU_AUDIO2                 182
#define IDC_EXIT                        1000
#define PIC_VIDEO                       1001
#define PIC_AUDIO                       1002
#define IDC_CCTV2                       1003
#define IDC_DYCJ2                       1004
#define VOL_UP                          1005
#define VOL_DOWN                        1006
#define IDC_STATIC_SIGNAL               1007
#define IDC_STATIC_VOLUME               1008
#define IDC_STATIC_VIDEO                1009
#define IDC_EDIT1                       1010
#define IDC_STATIC_SCREEN               1012

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        183
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
