#ifndef DDBSDK_H
#define DDBSDK_H

#include "../platformHeader/platform.h"
#include <winioctl.h>
#include "../log/LocalLog.h"

#define DDBSDK_VERSION   0x00000501


#define FILE_DEVICE_DDBSDK					0x00001000

#define IOCTL_DDBSDK_DMB_START_DEVICE		CTL_CODE(FILE_DEVICE_DDBSDK, 0x0001, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_DMB_START_SERVICE		CTL_CODE(FILE_DEVICE_DDBSDK, 0x0002, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_DMB_STOP_SERVICE		CTL_CODE(FILE_DEVICE_DDBSDK, 0x0003, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_DMB_STOP_DEVICE		CTL_CODE(FILE_DEVICE_DDBSDK, 0x0004, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_DDBSDK_RECONFIGURE			CTL_CODE(FILE_DEVICE_DDBSDK, 0x0011, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_VERSIONINFO			CTL_CODE(FILE_DEVICE_DDBSDK, 0x0012, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_OPEN_DMBDEVICE			CTL_CODE(FILE_DEVICE_DDBSDK, 0x0013, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_CLOSE_DMBDEVICE		CTL_CODE(FILE_DEVICE_DDBSDK, 0x0014, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_DMBSIGNAL_QUALITY				CTL_CODE(FILE_DEVICE_DDBSDK, 0x0015, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_CA_AUTHORIZED_INFO				CTL_CODE(FILE_DEVICE_DDBSDK, 0x0016, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_DDBSDK_GET_CA_PROMPTMESSAGE			CTL_CODE(FILE_DEVICE_DDBSDK, 0x0016, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_GETCA_PROMPTMSG_TRAFFIC		CTL_CODE(FILE_DEVICE_DDBSDK, 0x0017, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_GETCA_PROMPTMSG_WEATHER		CTL_CODE(FILE_DEVICE_DDBSDK, 0x0018, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_GETCA_PROMPTMSG_FINANCE		CTL_CODE(FILE_DEVICE_DDBSDK, 0x0019, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_GETCA_PROMPTMSG_POIINFO		CTL_CODE(FILE_DEVICE_DDBSDK, 0x001a, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_GETCA_PROMPTMSG_DOWNFILE		CTL_CODE(FILE_DEVICE_DDBSDK, 0x001b, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_GET_DATETIME					CTL_CODE(FILE_DEVICE_DDBSDK, 0x001c, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_DDBSDK_LIST_DATAPROGRAM		CTL_CODE(FILE_DEVICE_DDBSDK, 0x0020, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_OPEN_DATA_XXXX			CTL_CODE(FILE_DEVICE_DDBSDK, 0x0021, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_GET_DATA_XXXX			CTL_CODE(FILE_DEVICE_DDBSDK, 0x0022, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_CLOSE_DATA_XXXX		CTL_CODE(FILE_DEVICE_DDBSDK, 0x0023, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_DDBSDK_DATA_PID_OPEN			CTL_CODE(FILE_DEVICE_DDBSDK, 0x0024, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_DATA_PID_GET			CTL_CODE(FILE_DEVICE_DDBSDK, 0x0025, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_DATA_PID_CLOSE			CTL_CODE(FILE_DEVICE_DDBSDK, 0x0026, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_DDBSDK_DATA_TS_OPEN			CTL_CODE(FILE_DEVICE_DDBSDK, 0x0027, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_DATA_TS_GET			CTL_CODE(FILE_DEVICE_DDBSDK, 0x0028, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_DATA_TS_CLOSE			CTL_CODE(FILE_DEVICE_DDBSDK, 0x0029, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_DDBSDK_LIST_VIDEOPROGRAM		CTL_CODE(FILE_DEVICE_DDBSDK, 0x0030, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_OPEN_VIDEO				CTL_CODE(FILE_DEVICE_DDBSDK, 0x0031, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_GET_VIDEO_ONEFRAMEVIDEO	CTL_CODE(FILE_DEVICE_DDBSDK, 0x0033, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_GET_VIDEO_ONEFRAMEAUDIO	CTL_CODE(FILE_DEVICE_DDBSDK, 0x0034, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_GET_VIDEO_PCR				CTL_CODE(FILE_DEVICE_DDBSDK, 0x0035, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_CLOSE_VIDEO				CTL_CODE(FILE_DEVICE_DDBSDK, 0x0036, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_CHANGE_VIDEO_CHAL			CTL_CODE(FILE_DEVICE_DDBSDK, 0x0037, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_DDBSDK_LIST_MUSICAMPROGRAM	CTL_CODE(FILE_DEVICE_DDBSDK, 0x0040, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_OPEN_MUSICAM		CTL_CODE(FILE_DEVICE_DDBSDK, 0x0041, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_GET_MUSICAM_DATA	CTL_CODE(FILE_DEVICE_DDBSDK, 0x0042, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_CLOSE_MUSICAM		CTL_CODE(FILE_DEVICE_DDBSDK, 0x0043, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_CHANGE_MUSICAM_CHAL		CTL_CODE(FILE_DEVICE_DDBSDK, 0x0044, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_DDBSDK_OPEN_DATA_FINANCE	CTL_CODE(FILE_DEVICE_DDBSDK, 0x0051, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_GET_DATA_FINANCE	CTL_CODE(FILE_DEVICE_DDBSDK, 0x0052, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_CLOSE_DATA_FINANCE	CTL_CODE(FILE_DEVICE_DDBSDK, 0x0053, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_DDBSDK_OPEN_DATA_TRAFFIC	CTL_CODE(FILE_DEVICE_DDBSDK, 0x0061, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_GET_DATA_TRAFFIC	CTL_CODE(FILE_DEVICE_DDBSDK, 0x0062, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_CLOSE_DATA_TRAFFIC	CTL_CODE(FILE_DEVICE_DDBSDK, 0x0063, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_DDBSDK_OPEN_DATA_WEATHER	CTL_CODE(FILE_DEVICE_DDBSDK, 0x0071, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_GET_DATA_WEATHER	CTL_CODE(FILE_DEVICE_DDBSDK, 0x0072, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_CLOSE_DATA_WEATHER	CTL_CODE(FILE_DEVICE_DDBSDK, 0x0073, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_DDBSDK_OPEN_DATA_PIOINFO	CTL_CODE(FILE_DEVICE_DDBSDK, 0x0081, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_GET_DATA_PIOINFO	CTL_CODE(FILE_DEVICE_DDBSDK, 0x0082, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_CLOSE_DATA_PIOINFO	CTL_CODE(FILE_DEVICE_DDBSDK, 0x0083, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_DDBSDK_LIST_DATA_DOWNLOADINGFILESTATUS		CTL_CODE(FILE_DEVICE_DDBSDK, 0x0091, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_GET_DATA_ONEFILEINFO					CTL_CODE(FILE_DEVICE_DDBSDK, 0x0092, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_OPEN_DATA_DOWNLOADFILE					CTL_CODE(FILE_DEVICE_DDBSDK, 0x0093, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_CLOSE_DATA_DOWNLOADFILE				CTL_CODE(FILE_DEVICE_DDBSDK, 0x0094, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_GETONEDATABLOCK_FINISHEDFILE_OPEN		CTL_CODE(FILE_DEVICE_DDBSDK, 0x0095, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_GETONEDATABLOCK_FINISHEDFILE			CTL_CODE(FILE_DEVICE_DDBSDK, 0x0096, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_GETONEDATABLOCK_FINISHEDFILE_CLOSE		CTL_CODE(FILE_DEVICE_DDBSDK, 0x0097, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_GET_ONE_FINISHEDFILE					CTL_CODE(FILE_DEVICE_DDBSDK, 0x0098, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_DDBSDK_OPEN_DATA_CARPARK						CTL_CODE(FILE_DEVICE_DDBSDK, 0x00E1, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_GET_DATA_CARPARK						CTL_CODE(FILE_DEVICE_DDBSDK, 0x00E2, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_CLOSE_DATA_CARPARK						CTL_CODE(FILE_DEVICE_DDBSDK, 0x00E3, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_DDBSDK_LIST_WEATHER_DOWNLOADINGFILESTATUS			CTL_CODE(FILE_DEVICE_DDBSDK, 0x00B1, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_GET_WEATHER_ONEFILEINFO					CTL_CODE(FILE_DEVICE_DDBSDK, 0x00B2, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_OPEN_WEATHER_DOWNLOADFILE					CTL_CODE(FILE_DEVICE_DDBSDK, 0x00B3, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_CLOSE_WEATHER_DOWNLOADFILE					CTL_CODE(FILE_DEVICE_DDBSDK, 0x00B4, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_WEATHER_GETONEDATABLOCK_FINISHEDFILE_OPEN	CTL_CODE(FILE_DEVICE_DDBSDK, 0x00B5, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_DDBSDK_WEATHER_GETONEDATABLOCK_FINISHEDFILE		CTL_CODE(FILE_DEVICE_DDBSDK, 0x00B6, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_DDBSDK_WEATHER_GETONEDATABLOCK_FINISHEDFILE_CLOSE	CTL_CODE(FILE_DEVICE_DDBSDK, 0x00B7, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_DDBSDK_WEATHER_GET_ONE_FINISHEDFILE				CTL_CODE(FILE_DEVICE_DDBSDK, 0x00B8, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_DDBSDK_LIST_ROADCONDITION_DOWNLOADINGFILESTATUS			CTL_CODE(FILE_DEVICE_DDBSDK, 0x00C1, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_GET_ROADCONDITION_ONEFILEINFO						CTL_CODE(FILE_DEVICE_DDBSDK, 0x00C2, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_OPEN_ROADCONDITION_DOWNLOADFILE					CTL_CODE(FILE_DEVICE_DDBSDK, 0x00C3, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_CLOSE_ROADCONDITION_DOWNLOADFILE					CTL_CODE(FILE_DEVICE_DDBSDK, 0x00C4, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_ROADCONDITION_GETONEDATABLOCK_FINISHEDFILE_OPEN	CTL_CODE(FILE_DEVICE_DDBSDK, 0x00C5, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_DDBSDK_ROADCONDITION_GETONEDATABLOCK_FINISHEDFILE			CTL_CODE(FILE_DEVICE_DDBSDK, 0x00C6, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_DDBSDK_ROADCONDITION_GETONEDATABLOCK_FINISHEDFILE_CLOSE	CTL_CODE(FILE_DEVICE_DDBSDK, 0x00C7, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_DDBSDK_ROADCONDITION_GET_ONE_FINISHEDFILE					CTL_CODE(FILE_DEVICE_DDBSDK, 0x00C8, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_DDBSDK_LIST_EMERGENCYBRO_DOWNLOADINGFILESTATUS			CTL_CODE(FILE_DEVICE_DDBSDK, 0x00D1, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_GET_EMERGENCYBRO_ONEFILEINFO						CTL_CODE(FILE_DEVICE_DDBSDK, 0x00D2, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_OPEN_EMERGENCYBRO_DOWNLOADFILE						CTL_CODE(FILE_DEVICE_DDBSDK, 0x00D3, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_CLOSE_EMERGENCYBRO_DOWNLOADFILE					CTL_CODE(FILE_DEVICE_DDBSDK, 0x00D4, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_EMERGENCYBRO_GETONEDATABLOCK_FINISHEDFILE_OPEN		CTL_CODE(FILE_DEVICE_DDBSDK, 0x00D5, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_DDBSDK_LIST_TRAVELFILE_DOWNLOADINGFILESTATUS				CTL_CODE(FILE_DEVICE_DDBSDK, 0x00D6, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_GET_TRAVELFILE_ONEFILEINFO							CTL_CODE(FILE_DEVICE_DDBSDK, 0x00D7, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_OPEN_TRAVELFILE_DOWNLOADFILE						CTL_CODE(FILE_DEVICE_DDBSDK, 0x00D8, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_CLOSE_TRAVELFILE_DOWNLOADFILE						CTL_CODE(FILE_DEVICE_DDBSDK, 0x00D9, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_TRAVELFILE_GETONEDATABLOCK_FINISHEDFILE_OPEN		CTL_CODE(FILE_DEVICE_DDBSDK, 0x00DA, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_DDBSDK_LIST_EXPOFILE_DOWNLOADINGFILESTATUS				CTL_CODE(FILE_DEVICE_DDBSDK, 0x00DB, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_GET_EXPOFILE_ONEFILEINFO							CTL_CODE(FILE_DEVICE_DDBSDK, 0x00DC, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_OPEN_EXPOFILE_DOWNLOADFILE							CTL_CODE(FILE_DEVICE_DDBSDK, 0x00DD, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_CLOSE_EXPOFILE_DOWNLOADFILE						CTL_CODE(FILE_DEVICE_DDBSDK, 0x00DE, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_EXPOFILE_GETONEDATABLOCK_FINISHEDFILE_OPEN			CTL_CODE(FILE_DEVICE_DDBSDK, 0x00DF, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_DDBSDK_EMERGENCYBRO_GETONEDATABLOCK_FINISHEDFILE			CTL_CODE(FILE_DEVICE_DDBSDK, 0x00D6, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_DDBSDK_EMERGENCYBRO_GETONEDATABLOCK_FINISHEDFILE_CLOSE	CTL_CODE(FILE_DEVICE_DDBSDK, 0x00D7, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_DDBSDK_EMERGENCYBRO_GET_ONE_FINISHEDFILE					CTL_CODE(FILE_DEVICE_DDBSDK, 0x00D8, METHOD_BUFFERED, FILE_ANY_ACCESS)

/* this ioctl macro is only used for software test */
#define IOCTL_DDBSDK_FILEINPUT_TEST		CTL_CODE(FILE_DEVICE_DDBSDK, 0x00a1, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_SET_FILEINPUT_TEST_MODE	CTL_CODE(FILE_DEVICE_DDBSDK, 0x00a2, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_CANCEL_FILEINPUT_TEST_MODE	CTL_CODE(FILE_DEVICE_DDBSDK, 0x00a3, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_DDBSDK_TS_STREAM_OPEN										CTL_CODE(FILE_DEVICE_DDBSDK, 0x00F1, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_TS_STREAM_GET										CTL_CODE(FILE_DEVICE_DDBSDK, 0x00F2, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DDBSDK_TS_STREAM_CLOSE									CTL_CODE(FILE_DEVICE_DDBSDK, 0x00F3, METHOD_BUFFERED, FILE_ANY_ACCESS)



/*ERROR Code define*/
#define CA_INTIAL_ERROR					0x00001001  //CA初始化失败
#define DMB_START_FAILED				0x00000001	//DMB设备开启失败
#define OPENDEVICE_GET_TDT_TIMEOUT		0x00000002	//opendevice获取时间超时
#define REGSET_DMBDEVICE_FIALD			0x00001002	//注册DMB设备失败
#define DDBSDK_NOT_AUTHORIZED			0x00001003	//DDBSDK未授权
#define TRAFFIC_DATA_CA_UNAUTH			0x00002001	//交通数据CA未授权
#define WEATHER_DATA_CA_UNAUTH			0x00002002	//天气数据CA未授权
#define FINANCE_DATA_CA_UNAUTH			0x00002003	//财经数据CA未授权
#define POIINFO_DATA_CA_UNAUTH			0x00002004	//影院数据CA未授权
#define DOWNFILE_DATA_CA_UNAUTH			0x00002005	//文件下载CA未授权




//获取CA信息的回调函数
typedef void (__stdcall * __stdcall ShowCAPromptMessage)(BYTE MesageNo); 



extern "C" void __declspec(dllexport)InitCAPromptMessage(ShowCAPromptMessage func);


/* data typedef  */
#define u8   unsigned char 
#define u16  unsigned short
#define u32  unsigned int
#define s8   signed char
#define s16  signed short
#define s32  signed int
#define s64  __int64
#define u64  unsigned __int64

/* 设置存放DDBSDK .dll, CAFILE, 及其它下载文件的路径 */
#ifdef DDBSDK_PLATFORM_WLD_H
#define DDBSDK_MAINPATH_DEFAULT    "\\MMC_Storage"
#endif
#ifdef DDBSDK_PLATFORM_GUOWEI_H
#define DDBSDK_MAINPATH_DEFAULT    "\\Storage Card"
#endif
#ifdef DDBSDK_PLATFORM_MSD_H
#define DDBSDK_MAINPATH_DEFAULT    "\\StorageCard"
#endif
#define DDBSDK_MAINPATH_NAME       "\\ddbsdk"

/*************/

#define  PIDGOT(TSBUF)  (((TSBUF[1]) & 0x1f) << 8) | ((TSBUF[2]) & 0xFF)

#define   ODD_KEY    0x3
#define   EVEN_KEY   0x2
#define SWAP(TSBUF)  ((TSBUF[3] << 24) | (TSBUF[2] << 16) | (TSBUF[1] << 8) | TSBUF[0])

typedef struct _TSHEADER_INFO_
{
	unsigned sync_byte:         8;

	unsigned pid_5:             5;
	unsigned transport_piority: 1;
	unsigned start_indicator:   1;
	unsigned error_indicator:   1;

	unsigned pid_8:              8;

	unsigned continue_counter:   4;
	unsigned adaptation_control: 2;
	unsigned scrambling_control: 2;

} TsHeader_t;

enum {
	DDB_MUSICAM_CLASSIC947,
	DDB_MUSICAM_ENEWS,
	DDB_DATA,
	DDB_VIDEO_FIRSTFINANCE,
	DDB_VIDEO_CCTV5,
	DDB_MUSICAM_TRAFFIC
};

typedef struct ddbsdk_versionInfo_s ddbsdk_versionInfo_t;

#define  MAX_DATA_PROGRAM_NUM   10
#define  MAX_VIDEO_PROGRAM_NUM  5
#define  MAX_MUSICAM_PROGRAM_NUM  5
typedef struct _DDBSDK_
{
	unsigned finance_open: 1;
	unsigned pioinfo_open: 1;
	unsigned traffic_open: 1;
	unsigned weather_open: 1;
	unsigned sysfile_open: 1;
	unsigned filedown_open: 1;
	unsigned device_open:   1;
	unsigned serviceFile_open:  1;

	unsigned service_lock_flag: 1;   /* locked to only surpport one service at the same time */
	unsigned testInSMGLabFlag:  1;
	unsigned musicam_open:      1;
	unsigned pat_open:          1;
	unsigned pmt_open:          1;
	unsigned cat_open:          1;
	unsigned video_open:        1;
	unsigned videoScene_open:   1;

	unsigned videoOdr_open:					1;
	unsigned tdt_open:						1;
	unsigned ca_init_ok:					1;
	unsigned test_file_mode:				1;
	/*-----------------后来增加------------------*/
	unsigned carpark_open:					1;
	unsigned weatherfile_open:				1;
	unsigned roadconditionsfile_open:		1;
	unsigned emergencybroadcastfile_open:	1;

	unsigned ts_stream_open:				1;
	unsigned isAuthorized:					1;
	unsigned dataService_open:				1;
	unsigned travelfile_open:				1;

	unsigned expofile_open:					1;
	unsigned decryp_data_ts_open:			1;
	unsigned reserved:						2;

	BOOL	haveDataList;

	HANDLE  hFinance;
	HANDLE  hTraffic;
	HANDLE  hWeather;
	HANDLE  hDownloadFile;
	HANDLE  hPIOInfo;
	HANDLE  hSysFile;
	HANDLE  hServiceFile;
	HANDLE  hMusicam;
	HANDLE  hPAT;
	HANDLE  hPMT;
	HANDLE  hCAT;
	HANDLE  hDmbVideo;
	HANDLE  hDmbAudio;
	HANDLE  hDmbScene;
	HANDLE  hDmbOdr;
	HANDLE  hTDT;
	/*-----后来增加-----*/
	HANDLE  hCarPark;
	HANDLE	hWeatherFile;
	HANDLE	hRoadConditionFile;
	HANDLE	hEmergencyBroadcastFile;
	HANDLE	ts_Stream;
	HANDLE	hTravelFile;
	HANDLE	hExpoFile;
	HANDLE	hDecrypDataTs;

	unsigned short device_open_count;
	int   serviceIndexCur;
	u32   frequency;
	u64   videoProgramPCR;
	u16   pcr_pid;
	u16   mjdDate;
	u32   tdtTime;
	char  ddbsdk_path_main[32];

}ddbsdk_t;


/*
  following data struct used for usrer Application's INTERFACE
*/

/* following used fo ioctl: IOCTL_DDBSDK_RECONFIGURE */
typedef struct ddbsdk_reconfigure_s
{
	unsigned testInSMGLabFlag : 1;
	unsigned reserved : 7;
	u32	   frequency;
	char   ddbsdk_path_main[32];

}ddbsdk_reconfigure_t;

/* following used fo ioctl: IOCTL_DDBSDK_VERSIONINFO */
struct ddbsdk_versionInfo_s
{
	u32    ddbsdk_version;  //举例: 如果是0x00000302意思就是版本0.3.2。
	u32    ca_version;      //举例: 如果是0x01020304意思就是版本1.2.3.4。
	u32    ca_card_no;      //ca 软卡卡号
	char   ca_ManuName[32];     //ca 厂商名
	char   ca_TvsName[32];      //TV 运营商名
};

/* following used fo ioctl:  
IOCTL_DDBSDK_LIST_DATA_DOWNLOADINGFILESTATUS
IOCTL_DDBSDK_GET_DATA_ONEFILEINFO
IOCTL_DDBSDK_OPEN_DATA_DOWNLOADFILE
IOCTL_DDBSDK_CLOSE_DATA_DOWNLOADFILE
IOCTL_DDBSDK_GETONEDATABLOCK_FINISHEDFILE_OPEN
IOCTL_DDBSDK_GETONEDATABLOCK_FINISHEDFILE
IOCTL_DDBSDK_GETONEDATABLOCK_FINISHEDFILE_CLOSE
*/
enum {
	SYSTEMFILE = 0x00,
	MULTIMEDIAFILE = 0x01,
	ADFILE = 0x02,
	CDMUSICFILE = 0x03,
	NETFILE = 0x04,
	POIFOODFILE = 0x05,
	PROGRAMFILE = 0xfd,
	LISTFILE = 0xfe
};

enum deDataType
{
	Traffic,
	Weather,
	Finance,
	POI,
	DownloadFile,
	RoadCondition,
	CarPark,
	EmergencyBroadcast,
	WeatherFile,
	TravelFile,
	ExpoFile
};

//错误消息结构
typedef struct ddbsdk_errormessage_s
{
	unsigned int errorCode;
	char errorMessage[60];
}ddbsdk_errorMessage;


#define MAXLISTFILEID   1024
typedef struct ddbsdk_servFileStatus_s
{
	int   numDownloading;
	int   numFinished;
	u32   selectedFILE_TYPE;    /* 列举时应该设置此值 */
	unsigned long   fileID_downing[MAXLISTFILEID];     /* 列举出数据类型为selectedFILE_TYPE的正在下载的文件 */
	unsigned long   fileID_finished[MAXLISTFILEID];    /* 列举出数据类型为selectedFILE_TYPE的下载完成的文件 */

}ddbsdk_servFileStatus_t;

typedef struct ddbsdk_servFileInfo_s
{
	u32   selectedFILE_ID;      /* GET文件数据或文件信息时，设置此值 */
	u32   FILE_LENGTH;
	 u8   FILE_TYPE;
	 u8   Version;
	u16   FILE_VALID_ENDDATE;
	u16   FILE_VALID_ENDTIME;
	u16   Block_length;
	u16   Block_num;

	/* parameter for FILE transfer */
	FILE * file_get;

}ddbsdk_servFileInfo_t;

/* following used fo ioctl:  
IOCTL_DDBSDK_LIST_VIDEOPROGRAM
IOCTL_DDBSDK_OPEN_VIDEO
IOCTL_DDBSDK_GET_VIDEO_ONEFRAMEVIDEO
IOCTL_DDBSDK_GET_VIDEO_ONEFRAMEAUDIO
IOCTL_DDBSDK_GET_VIDEO_PCR
IOCTL_DDBSDK_CLOSE_VIDEO
IOCTL_DDBSDK_CHANGE_VIDEO_CHAL
*/

typedef struct _DDBSDK_AVC_DEC_SPEC_INFO_
{
	u8   configureationVersion; /* 8, =1(const) */
	u8   AVCprofileIndication;  /* 8 */
	u8   profile_compatibility; /* 8 */
	u8   AVClevelIndication;    /* 8 */
	s8   lengthSizeMinusOne;    /* 2 */

	s8    numOfSequenceParameterSets;  /* 5 */
	u16   sequenceParameterLength;    /* 16 */
	u8    sps[32];

	u8    numOfPictureParamterSets;   /* 8 */
	u16   pictureParameterSetLength;    /* 16 */
	u8    pps[32];
}ddbsdk_avcDecoderSpecInfo;

typedef struct _DDBSDK_AAC_DEC_SPEC_INFO_
{
	  s8   audioObjectType;  /* 5 */
	  s8   samplingFrequencyIndex;  /* 4 */
	 s32   samplingFrequency;  /* 24 */
	  s8   channelConfiguration; /* 4 */
	  s8   sbrPresentFlag;
	  s8   extensionAudioObjectType;
	  s8   extensionSamplingFrequencyIndex; /* 4  */
	 s32   extensionSamplingFrequency;  /* 24 */

}ddbsdk_aacDecoderSpecInfo;

#define   MAX_VIDEO_PROGRAM   4
#define   MAX_DATA_PROGRAM    16
typedef struct ddbsdk_videoInfo_s ddbsdk_videoInfo_t;
struct ddbsdk_videoInfo_s
{
	u16   serviceNo;
	u16   ServiceIndex;
	u16   video_pid;
	u16   audio_pid;
	u16   scene_pid;
	u16   odr_pid;
	u16   ecm_pid;
	u16   emm_pid;
	u16   pcr_pid;
	u64   pcr_base;
	char   descr[32];

	ddbsdk_avcDecoderSpecInfo   avcDecInfo;
	ddbsdk_aacDecoderSpecInfo   aacDecInfo;

	ddbsdk_videoInfo_t * next;
};
typedef struct ddbsdk_dmbvideoInfo_s
{
	u32   ServiceNum;
	u32   selectServiceNo;
	ddbsdk_videoInfo_t   videoInfo[MAX_VIDEO_PROGRAM];
	
}ddbsdk_dmbvideoInfo_t;

/* following used fo ioctl:  
IOCTL_DDBSDK_LIST_MUSICAMPROGRAM
IOCTL_DDBSDK_OPEN_MUSICAM
IOCTL_DDBSDK_GET_MUSICAM_DATA
IOCTL_DDBSDK_CLOSE_MUSICAM
IOCTL_DDBSDK_CHANGE_MUSICAM_CHAL
*/
#define   MAX_MUSICAM_PROGRAM   16
typedef struct ddbsdk_musicamInfo_s ddbsdk_musicamInfo_t;
struct ddbsdk_musicamInfo_s
{
	u16   serviceNo;
	u16   ServiceIndex;
	char   descr[32];
	ddbsdk_musicamInfo_t * next;
};
typedef struct ddbsdk_dmbmusicamInfo_s
{
	u32   ServiceNum;
	u32   selectServiceNo;
	ddbsdk_musicamInfo_t   musicamInfo[MAX_MUSICAM_PROGRAM];
	
}ddbsdk_dmbmusicamInfo_t;

/* following used fo ioctl:  
IOCTL_DDBSDK_LIST_DATAPROGRAM
IOCTL_DDBSDK_OPEN_DATA_XXXX
IOCTL_DDBSDK_GET_DATA_XXXX
IOCTL_DDBSDK_CLOSE_DATA_XXXX
*/
typedef struct ddbsdk_dataInfo_s ddbsdk_dataInfo_t;
struct ddbsdk_dataInfo_s
{
	u16   serviceNo;
	u16   ServiceIndex;
	u16   data_pid;
	u16   ecm_pid;
	u16   emm_pid;
	 u8   stream_type;  /*db: traffic, dc: weather, dd: finance,
						de: system file, df: file, e1: PIO, fc: 文件清清单*/
	char   descr[32];
	ddbsdk_dataInfo_t * next;
};
typedef struct ddbsdk_dmbdataInfo_s
{
	u32   ServiceNum;
	u32   selectServiceNo;
	ddbsdk_dataInfo_t   dataInfo[MAX_DATA_PROGRAM];

}ddbsdk_dmbdataInfo_t;

typedef struct _DDBSDK_DATETIME_
{
	u16		year;
	u8		month;
	u8		day;
	u8		hour;
	u8		minute;
	u8		second;
}ddbsdk_datetime;

class ddbsdk_decryp_program_info
{
public:
	u16		prog_pid;
	u16		ecm_pid;
	u16		emm_pid;
	BYTE	g_OddCW[16];	
	BYTE	g_EvenCW[16];
	bool	isHaveCW;

};

#endif

